In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('IMDB Dataset.csv')
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

# text preprocessing

In [3]:
df.drop_duplicates(inplace=True)

In [4]:
import re

# Convert all reviews to lowercase
df["review"] = df["review"].str.lower()

# Remove HTML tags
df["review"] = df["review"].apply(lambda x: re.sub(r'<.*?>', '', x))

# Remove special characters and numbers
df["review"] = df["review"].apply(lambda x: re.sub(r'[^a-zA-Z\s]', '', x))




df.head(10)

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production the filming tech...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically theres a family where a little boy j...  negative
4  petter matteis love in the time of money is a ...  positive
5  probably my alltime favorite movie a story of ...  positive
6  i sure would like to see a resurrection of a u...  positive
7  this show was an amazing fresh  innovative ide...  negative
8  encouraged by the positive comments about this...  negative
9  if you like original gut wrenching laughter yo...  positive

# Removing stopworks using NLTK

In [35]:
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

nltk.download('punkt')
nltk.download('stopwords')


stop_words = set(stopwords.words('english'))

df['review'] = df['review'].apply(lambda x: ' '.join([word for word in x.split() if word not in stop_words]))
df.head(10)

[nltk_data] Downloading package punkt to
[nltk_data]     e:\Pytorch_ML\env\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     e:\Pytorch_ML\env\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

                                              review  sentiment
0  one review mention watch oz episod youll hook ...          1
1  wonder littl product film techniqu unassum old...          1
2  thought wonder way spend time hot summer weeke...          1
3  basic famili littl boy jake think zombi closet...          0
4  petter mattei love time money visual stun film...          1
5  probabl alltim favorit movi stori selfless sac...          1
6  sure would like see resurrect date seahunt ser...          1
7  show amaz fresh innov idea first air first yea...          0
8  encourag posit comment film look forward watch...          0
9  like origin gut wrench laughter like movi youn...          1

# Stemming and lemm

In [6]:
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer


nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')

# Initialize tools
stop_words = set(stopwords.words('english'))
stemmer = PorterStemmer()


df['review'] = df['review'].apply(
    lambda x: ' '.join([
        stemmer.stem(word)
        for word in word_tokenize(str(x).lower())
        if word.isalnum() and word not in stop_words
    ])
)


df.head(10)

[nltk_data] Downloading package punkt to
[nltk_data]     e:\Pytorch_ML\env\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     e:\Pytorch_ML\env\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt_tab.zip.
[nltk_data] Downloading package stopwords to
[nltk_data]     e:\Pytorch_ML\env\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     e:\Pytorch_ML\env\nltk_data...
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     e:\Pytorch_ML\env\nltk_data...

                                              review sentiment
0  one review mention watch oz episod youll hook ...  positive
1  wonder littl product film techniqu unassum old...  positive
2  thought wonder way spend time hot summer weeke...  positive
3  basic there famili littl boy jake think there ...  negative
4  petter mattei love time money visual stun film...  positive
5  probabl alltim favorit movi stori selfless sac...  positive
6  sure would like see resurrect date seahunt ser...  positive
7  show amaz fresh innov idea first air first yea...  negative
8  encourag posit comment film look forward watch...  negative
9  like origin gut wrench laughter like movi youn...  positive

In [36]:

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer

nltk.download('punkt')
nltk.download('punkt_tab')  
nltk.download('wordnet')
nltk.download('omw-1.4')
nltk.download('stopwords')


lemmatizer = WordNetLemmatizer()
stop_words = set(stopwords.words('english'))

#Function for preprocessing (clean + reusable)
def preprocess(text):
    tokens = word_tokenize(str(text).lower())
    clean_words = [
        lemmatizer.lemmatize(word)
        for word in tokens
        if word.isalnum() and word not in stop_words
    ]
    return ' '.join(clean_words)

df['review'] = df['review'].apply(preprocess)

df.head(10)

[nltk_data] Downloading package punkt to
[nltk_data]     e:\Pytorch_ML\env\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     e:\Pytorch_ML\env\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     e:\Pytorch_ML\env\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     e:\Pytorch_ML\env\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     e:\Pytorch_ML\env\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

                                              review  sentiment
0  one review mention watch oz episod youll hook ...          1
1  wonder littl product film techniqu unassum old...          1
2  thought wonder way spend time hot summer weeke...          1
3  basic famili littl boy jake think zombi closet...          0
4  petter mattei love time money visual stun film...          1
5  probabl alltim favorit movi stori selfless sac...          1
6  sure would like see resurrect date seahunt ser...          1
7  show amaz fresh innov idea first air first yea...          0
8  encourag posit comment film look forward watch...          0
9  like origin gut wrench laughter like movi youn...          1

# LabelEncoder

In [37]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['sentiment'] = le.fit_transform(df['sentiment'])
df.head()

                                              review  sentiment
0  one review mention watch oz episod youll hook ...          1
1  wonder littl product film techniqu unassum old...          1
2  thought wonder way spend time hot summer weeke...          1
3  basic famili littl boy jake think zombi closet...          0
4  petter mattei love time money visual stun film...          1

In [38]:
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer


tf = TfidfVectorizer(max_features=6000)
x = tf.fit_transform(df['review']).toarray()
x.shape

(49582, 6000)

# Dataset and Dataloader

In [39]:
from sklearn.model_selection import train_test_split
import torch
from torch.utils.data import DataLoader, TensorDataset, Dataset

x_train, x_test, y_train, y_test = train_test_split(x, df['sentiment'], test_size=0.2, random_state=42)

train_set = TensorDataset(
    torch.tensor(x_train, dtype=torch.float32),
    torch.tensor(y_train.values, dtype=torch.long)
)
test_set = TensorDataset(
    torch.tensor(x_test, dtype=torch.float32),
    torch.tensor(y_test.values, dtype=torch.long)
)

train_dataloader = DataLoader(train_set, batch_size=64, shuffle=True)
test_dataloader = DataLoader(test_set, batch_size=64, shuffle=False)

# Build RNN Model

In [41]:
import torch.nn as nn
import torch.optim as optim

In [42]:
class RNN(nn.Module):
    def __init__(self, input_size, hidden_size, num_layers, num_classes):
        super(RNN, self).__init__()

        self.hidden_size = hidden_size
        self.num_layers = num_layers

        self.rnn = nn.RNN(input_size, hidden_size, num_layers, batch_first=True)
        self.fc = nn.Linear(hidden_size, num_classes)

    def forward(self, x):
        h0 = torch.zeros(self.num_layers, x.size(0), self.hidden_size).to(x.device)

        out, _ = self.rnn(x, h0)
        out = self.fc(out[:, -1, :])
        return out

In [43]:
input_size = x.shape[1]
hidden_size = 128
num_layers = 2
num_classes = 1 

model = RNN(input_size, hidden_size, num_layers, num_classes)


criterion = nn.BCEWithLogitsLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

In [44]:
num_epochs = 10

for epoch in range(num_epochs):
    model.train()
    total_loss = 0

    for Xb, yb in train_dataloader:
        optimizer.zero_grad()

        Xb = Xb.unsqueeze(1)   # (batch, seq_len=1, features)
        yb = yb.float()

        outputs = model(Xb).squeeze(1)  # safer squeeze

        loss = criterion(outputs, yb)

        loss.backward()
        optimizer.step()

        total_loss += loss.item()

    print(f'Epoch [{epoch+1}/{num_epochs}], Loss: {total_loss:.4f}')

Epoch [1/10], Loss: 198.2081
Epoch [2/10], Loss: 145.2258
Epoch [3/10], Loss: 135.5516
Epoch [4/10], Loss: 129.3935
Epoch [5/10], Loss: 126.0148
Epoch [6/10], Loss: 123.2378
Epoch [7/10], Loss: 120.6221
Epoch [8/10], Loss: 118.8069
Epoch [9/10], Loss: 117.0847
Epoch [10/10], Loss: 115.5685

In [46]:
model.eval()
with torch.no_grad():
    correct, total = 0, 0
    for Xb, yb in test_dataloader:
        Xb = Xb.unsqueeze(1)
        outputs = model(Xb).squeeze(1)
        predicted = (torch.sigmoid(outputs) > 0.5).long()
        total += yb.size(0)
        correct += (predicted == yb).sum().item()

    print(f'Test Accuracy: {correct / total:.4f}')

Test Accuracy: 0.8671